SELECT E.APELLIDO AS "Employee", M.APELLIDO AS "Manager"
        FROM INTEGRANTES E LEFT OUTER JOIN INTEGRANTES M 
          ON E.ID_MANAGER = M.ID_INTEGRANTE
        ORDER BY M.APELLIDO;

-- SELECT *
-- FROM EQUIPOS E, INTEGRANTES I
-- WHERE E.ID_EQUIPO = I.ID_EQUIPO