DROP DATABASE IF EXISTS PROYECTOS;

CREATE DATABASE IF NOT EXISTS PROYECTOS;

USE PROYECTOS;

CREATE TABLE IF NOT EXISTS EQUIPOS (
    ID_EQUIPO VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_EQUIPO)
);

CREATE TABLE IF NOT EXISTS INTEGRANTES (
    ID_INTEGRANTE VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL,
    ID_MANAGER VARCHAR(255),
    PRIMARY KEY (ID_INTEGRANTE),
    FOREIGN KEY (ID_MANAGER) REFERENCES INTEGRANTES(ID_INTEGRANTE)
);

CREATE TABLE IF NOT EXISTS EQUIPOS_INTEGRANTES (
    ID_EQUIPOS_INTEGRANTES INT NOT NULL AUTO_INCREMENT,
    ID_EQUIPO VARCHAR(255) NOT NULL,
    ID_INTEGRANTE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_EQUIPOS_INTEGRANTES),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
    FOREIGN KEY (ID_INTEGRANTE) REFERENCES INTEGRANTES(ID_INTEGRANTE)
);

INSERT INTO EQUIPOS (ID_EQUIPO, NOMBRE)
VALUES ('ED001', 'Desarrollo Comercial'); 

INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A001', 'Bridget', 'Allen', 'Gerente de Proyectos', NULL); 
INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A011', 'Percy', 'Gates', 'Lider Tecnico', 'A001'); 
INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A111', 'Phoebe', 'Shields', 'Desarrollador Backend', 'A011'); 
INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A002', 'Elijah', 'Silva', 'Desarrollador Frontend', 'A011'); 
INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A012', 'Luke', 'Antcliff', 'Disenador Web', 'A011'); 
INSERT INTO INTEGRANTES (ID_INTEGRANTE, NOMBRE, APELLIDO, ROL, ID_MANAGER)
VALUES ('A112', 'Darlene', 'Corbett', 'Tester', 'A011');

INSERT INTO EQUIPOS_INTEGRANTES (ID_EQUIPO, ID_INTEGRANTE)
VALUES ('ED001', 'A011');
INSERT INTO EQUIPOS_INTEGRANTES (ID_EQUIPO, ID_INTEGRANTE)
VALUES ('ED001', 'A111');
INSERT INTO EQUIPOS_INTEGRANTES (ID_EQUIPO, ID_INTEGRANTE)
VALUES ('ED001', 'A002');
INSERT INTO EQUIPOS_INTEGRANTES (ID_EQUIPO, ID_INTEGRANTE)
VALUES ('ED001', 'A012');
INSERT INTO EQUIPOS_INTEGRANTES (ID_EQUIPO, ID_INTEGRANTE)
VALUES ('ED001', 'A112');


